### ISSUE TITLE
What's the status of the level 0 spec?

### ISSUE THREAD

**Issue by jonco3** [whatwg/loader#101]
As I understood it there was going to be a mininal "level 0" specification produced before the full spec was finialised.  Is that still correct?  I see a few issues mentioning "milestone 0" but nothing formal.  It would be great to have something concrete written down to implement before the main spec is
finished.

**Comment by caridy** [comment]
@jonco3 from my side, we are still finishing some small details (error tracking and propagation) on the Loader API before jumping into the fetch and name resolution spec parts. We will be trying to lift the loader api back into 262, and I think it could happen very soon, we will see.

**Comment by domenic** [comment]
@caridy I don't see an answer to @jonco3's question in there? Is the implicit answer that the level 0 idea has been abandoned, in favor of working on the loader API?

I think this would be very disappointing, and I don't believe the loader API will be accepted into 262 in this state, since it is not implementable as-is, and we have no implementation experience to tell us whether it's a good API.

**Comment by caridy** [comment]
we are not abandoning that idea, as I mentioned, I will like to jump into the missing pieces (fetch and name resolution) in few days once I finish the issues with the promises and the error control (the thing that you helped me with few days ago). The 262 lifting process was just a side note, which will not block stage 0.

**Comment by jonco3** [comment]
Great, thanks for the update.
