### ISSUE TITLE
Discussion and reasoning behind initial draft

### ISSUE THREAD

**Issue by sheerun** [whatwg/loader#6]
Where can I find discussion and reasoning behind Loader API introduced first commit?

I can't find anything like it in last ES6 draft that included Loader API (August 24, 2014 Draft Rev 27). The Loader API in this repository seems quite different from what I found in it.

I can't find any discussion about this on mailing list too.

**Comment by dherman** [comment]
What was in the earlier ES6 drafts was Allen's attempt to transcribe the work the modules champions had done in late 2013, but after the Boston TC39 meeting we decided to split out the loader spec. Since then the modules champions have been hacking on the spec further, and we've been making a lot of simplifications. I'm still hacking on the spec but I will try to write up some of the reasoning and I'm happy to discuss any and all of it.

**Comment by dherman** [comment]
BTW I think it makes sense to keep using this repo's issue tracker for logged discussions, and I'll also hang out in #loader on freenode. (I use IRCCloud so if I'm not around you can still leave me messages and I can get them later.)

**Comment by dherman** [comment]
I've also started a [rationale doc](../blob/master/rationale.md) to capture the reasoning behind design decisions.
